[package]
name = "todo"
version = "0.1.0"
authors = ["CircuitFire <ced9088@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
frames = {git = "https://github.com/CircuitFire/frames.git"}